 version: "3.7"

 services:
   ckpool-docker:
     image: ckpool-docker
     ports:
       - 3333:3333
     extra_hosts:
       - ckpool.local:host-gateway
     volumes:
       - ${PWD}/conf:/srv/ckpool/conf
       - ${PWD}/logs:/srv/ckpool/logs
     restart: unless-stopped
